In [1]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
a[1,5] = 20
#a[:,2] = 5
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [22]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)
b[0,1,1]

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


4

In [23]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [25]:
a = np.array([1,2,3,4])
print(a)
b = np.array([1,0,1,0])
a + b

[1 2 3 4]


array([2, 2, 4, 4])

In [27]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.sum(stats, axis = 1)

array([ 6, 15])

In [38]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [39]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
np.shape(np.vstack([v1,v2,v1,v2]))

(4, 4)

In [50]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

print(np.hstack((h1,h2)))
np.shape(np.hstack((h1,h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


(2, 6)

In [54]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedate = filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [62]:
print(np.where(filedata > 50))
filedata[0,4]

(array([0, 0, 1, 1, 1, 2, 2, 2, 2], dtype=int32), array([ 4,  5,  4,  5,  7,  4,  8, 16, 17], dtype=int32))


196.0

In [64]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [68]:
np.all(filedata > 50, axis = 1)

array([False, False, False])